//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public int CallID { get; set; }
        public int CustomerID { get; set; }
        public int BusinessDayID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Note { get; set; }
        public Nullable<int> Priority { get; set; }
        public int CallStatusID { get; set; }
        public Nullable<int> ServiceID { get; set; }
    }
}
