//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Call_tbl()
        {
            this.History_tbl = new HashSet<History_tbl>();
            this.Visit_tbl = new HashSet<Visit_tbl>();
            this.Visit_tbl1 = new HashSet<Visit_tbl>();
        }
    
        public int CallID { get; set; }
        public int CustomerID { get; set; }
        public int BusinessDayID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Note { get; set; }
        public int CallStatusID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual BusinessDay_tbl BusinessDay_tbl { get; set; }
        public virtual Customer_tbl Customer_tbl { get; set; }
        public virtual Service_tbl Service_tbl { get; set; }
        public virtual Status_tbl Status_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_tbl> History_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit_tbl> Visit_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit_tbl> Visit_tbl1 { get; set; }
    }
}
