//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission_tbl
    {
        public int PermissionID { get; set; }
        public int CompanyID { get; set; }
        public string Description { get; set; }
    
        public virtual Company_tbl Company_tbl { get; set; }
    }
}
