//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TopTechDBEntities : DbContext
    {
        public TopTechDBEntities()
            : base("name=TopTechDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessDay_tbl> BusinessDay_tbl { get; set; }
        public virtual DbSet<Call_tbl> Call_tbl { get; set; }
        public virtual DbSet<Company_tbl> Company_tbl { get; set; }
        public virtual DbSet<Customer_tbl> Customer_tbl { get; set; }
        public virtual DbSet<Employee_tbl> Employee_tbl { get; set; }
        public virtual DbSet<History_tbl> History_tbl { get; set; }
        public virtual DbSet<Service_tbl> Service_tbl { get; set; }
        public virtual DbSet<Status_tbl> Status_tbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Visit_tbl> Visit_tbl { get; set; }
        public virtual DbSet<Warehouse_tbl> Warehouse_tbl { get; set; }
        public virtual DbSet<Archive_tbl> Archive_tbl { get; set; }
    }
}
