//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit_tbl
    {
        public int VisitingID { get; set; }
        public int BusinessDayID { get; set; }
        public Nullable<System.TimeSpan> EstimatedTime { get; set; }
        public int CallID { get; set; }
        public int EmploeeID { get; set; }
        public int VisitStatusID { get; set; }
    
        public virtual BusinessDay_tbl BusinessDay_tbl { get; set; }
        public virtual Call_tbl Call_tbl { get; set; }
        public virtual Employee_tbl Employee_tbl { get; set; }
        public virtual Status_tbl Status_tbl { get; set; }
    }
}
